events {}

http {
    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            proxy_pass http://woerterbuch-frontend:3000;
        }

        location /api/ {
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;

            rewrite ^/api/(.*)$ /$1 break;
            proxy_pass http://woerterbuch-backend:6029;
        }
    }
}