name: woerterbuch

services:
  postgres:
    container_name: woerterbuch-postgres
    image: postgres:alpine3.17
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=secret
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d postgres"]
      interval: 1s
      retries: 3
    ports:
      - "5432:5432"
    volumes:
      - woerterbuch-postgres:/var/lib/postgresql/data
    networks:
      - woerterbuch-internal

  backend:
    container_name: woerterbuch-backend
    build:
      context: ../woerterbuch-backend
      dockerfile: Dockerfile
    env_file:
      - backend.dev.env
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - woerterbuch-internal
      - woerterbuch-external

  frontend:
    build:
      context: ../woerterbuch-frontend
      dockerfile: Dockerfile
    container_name: woerterbuch-frontend
    volumes:
      - ../woerterbuch-frontend/src:/app/src
    env_file:
      - frontend.env
    networks:
      - woerterbuch-external

  nginx:
    build:
      context: ../nginx
      dockerfile: Dockerfile
    container_name: woerterbuch-nginx
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
    networks:
      - woerterbuch-external


volumes:
  woerterbuch-postgres:

networks:
  woerterbuch-internal:
    driver: bridge
  woerterbuch-external:
    driver: bridge